name: Release helm chart

on:
  push:
    tags:
      - helm/v*.*.*
    branches-ignore:
      - '**'

  workflow_call:

env:
  REGISTRY_USER: motoki317
  CHART: test

jobs:
  release-helm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ env.REGISTRY_USER }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish chart
        run: |
          cd charts
          ./publish.sh ${{ env.CHART }} oci://ghcr.io/${{ env.REGISTRY_USER }}/charts
